INSERT INTO COZINHA (NOME) VALUES ('Tailandesa');
INSERT INTO COZINHA (NOME) VALUES ('Indiana');
INSERT INTO COZINHA (NOME) VALUES ('Brasileira');
INSERT INTO COZINHA (NOME) VALUES ('Argentina');

INSERT INTO RESTAURANTE (NOME, TAXA_FRETE) VALUES ('Thai Gourmet', 10);
INSERT INTO RESTAURANTE (NOME, TAXA_FRETE) VALUES ('Thai Delivery', 9.50);
INSERT INTO RESTAURANTE (NOME, TAXA_FRETE) VALUES ('Tuk Tuk Comida Indiana', 15);