INSERT INTO COZINHA (NOME) VALUES ('Tailandesa');
INSERT INTO COZINHA (NOME) VALUES ('Indiana');
INSERT INTO COZINHA (NOME) VALUES ('Brasileira');
INSERT INTO COZINHA (NOME) VALUES ('Argentina');

INSERT INTO RESTAURANTE (NOME, TAXA_FRETE, COZINHA_ID) VALUES ('Thai Gourmet', 10, 1);
INSERT INTO RESTAURANTE (NOME, TAXA_FRETE, COZINHA_ID) VALUES ('Thai Delivery', 9.50, 1);
INSERT INTO RESTAURANTE (NOME, TAXA_FRETE, COZINHA_ID) VALUES ('Tuk Tuk Comida Indiana', 15, 2);